### ISSUE TITLE
typst_basic.rs not rendering and also Segmentation Faulting

### ISSUE THREAD

**Issue by rousbound** [nixon-voxell/bevy_motiongfx#29] opened 2024-03-11 15:32 UTC
Hi! First of all, I'm thrilled by the looks of the project, congrats. 

However I faced some problems trying to execute the typst example.

Running the typst_basic.rs example did not result in any visual output. By checking the terminal logs:
```rust
2024-03-11T15:26:41.780148Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-03-11T15:26:41.780664Z  WARN winit::platform_impl::platform::x11::util::randr: XRandR reported that the display's 0mm in size, which is certifiably insane
2024-03-11T15:26:41.780801Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1
libEGL warning: DRI2: failed to authenticate
2024-03-11T15:26:41.863251Z  INFO bevy_render::renderer: AdapterInfo { name: "llvmpipe (LLVM 15.0.7, 256 bits)", vendor: 65541, device: 0, device_type: Cpu, driver: "llvmpipe", driver_info: "Mesa 23.0.4-0ubuntu1~22.04.1 (LLVM 15.0.7)", backend: Vulkan }
2024-03-11T15:26:42.218390Z  WARN naga_oil::compose::parse_imports: item list imports are deprecated, please use `rust::style::item_imports` (or use feature `allow_deprecated`)`
| #import bevy_render::view View

2024-03-11T15:26:43.873337Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux 22.04 Ubuntu", kernel: "6.5.0-21-generic", cpu: "12th Gen Intel(R) Core(TM) i9-12900K", core_count: "12", memory: "31.3 GiB" }
[
    SourceDiagnostic {
        severity: Error,
        span: Span(
            15673696619813,
        ),
        message: "file not found (searched at .\\assets/themes/Monokai Pro.tmTheme)",
        trace: [],
        hints: [],
    },
]
2024-03-11T15:26:44.006003Z  WARN naga_oil::compose::parse_imports: item list imports are deprecated, please use `rust::style::item_imports` (or use feature `allow_deprecated`)`
| #import bevy_render::view View

2024-03-11T15:26:44.009190Z  WARN naga_oil::compose::parse_imports: item list imports are deprecated, please use `rust::style::item_imports` (or use feature `allow_deprecated`)`
| #import bevy_render::view View
```

I suspected the error of 'file not found', and changed the typst code to not use the monokai theme:

```rust
    let content = String::from(
        r###"
        #set page(width: 1120pt, margin: 8pt)
        #set text(size: 24pt, font: "consolas", fill: rgb("#FCFCFA"))

        #show raw: set text(font: "Consolas")

        #box()[
            #text(fill: gradient.linear(rgb("#13A8C1"), rgb("#21C0AA")))[= Typst]
        ]

        $ frac(a^2, 2) $
        $ vec(1, 2, delim: "[") $
        $ mat(1, 2; 3, 4) $
        $ lim_x = op("lim", limits: #true)_x $

        ```rs
        fn main() {
            println!("Hello from Typst!");
        }
        ```
        "###,
    );
  ```

And it segmentation faulted. I tried different stuff like removing the raw part of the typst code, etc. It also segmentation faulted.

**Comment by nixon-voxell** [comment] 2024-03-11 15:44
The theme file is in there hmm.. are you running the code using cargo run --example typst_basic?

**Comment by rousbound** [comment] 2024-03-11 17:11
> The theme file is in there hmm.. are you running the code using cargo run --example typst_basic?

Yes, that's exactly what I'm doing. Tried both on the root of the project and inside examples folder.

**Comment by nixon-voxell** [comment] 2024-03-12 01:41
I see. Could I get the error log of the segmentation fault? Thanks.

**Comment by rousbound** [comment] 2024-03-14 02:47
Sure!

Here is what happens when I delete the following line from the "content" variable:
```typst
#set raw(theme: "themes/Monokai Pro.tmTheme")
```

```rust
[user@machine  in .../Tests/bevy_motiongfx]
 >> $ cargo run --example typst_basic
   Compiling bevy_motiongfx v0.1.0 (Tests/bevy_motiongfx)
    Finished dev [unoptimized + debuginfo] target(s) in 28.29s
     Running `target/debug/examples/typst_basic`
2024-03-14T02:44:52.344013Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-03-14T02:44:52.352428Z  WARN winit::platform_impl::platform::x11::util::randr: XRandR reported that the display's 0mm in size, which is certifiably insane
2024-03-14T02:44:52.356544Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1
libEGL warning: DRI2: failed to authenticate
2024-03-14T02:44:52.429928Z  INFO bevy_render::renderer: AdapterInfo { name: "llvmpipe (LLVM 15.0.7, 256 bits)", vendor: 65541, device: 0, device_type: Cpu, driver: "llvmpipe", driver_info: "Mesa 23.0.4-0ubuntu1~22.04.1 (LLVM 15.0.7)", backend: Vulkan }
2024-03-14T02:44:52.756528Z  WARN naga_oil::compose::parse_imports: item list imports are deprecated, please use `rust::style::item_imports` (or use feature `allow_deprecated`)`
| #import bevy_render::view View

2024-03-14T02:44:54.308229Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux 22.04 Ubuntu", kernel: "6.5.0-25-generic", cpu: "12th Gen Intel(R) Core(TM) i9-12900K", core_count: "12", memory: "31.3 GiB" }
2024-03-14T02:44:54.315468Z  INFO compile: typst: Layout iteration 0
2024-03-14T02:44:54.315536Z  INFO compile:Content::layout_root: typst::layout: Starting layout
2024-03-14T02:44:54.701294Z  INFO compile:Content::layout_root:DocumentElem::layout_root: typst::model::document: Document layout
2024-03-14T02:44:54.701339Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Page layout
2024-03-14T02:44:54.701421Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.701648Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout:FlowElem::layout:FlowLayouter::layout_par:ParElement::layout:BoxElem::layout:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.701996Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout:FlowElem::layout:FlowLayouter::layout_par:ParElement::layout:BoxElem::layout:Content::layout:FlowElem::layout:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.702110Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout:FlowElem::layout:FlowLayouter::layout_par:ParElement::layout:BoxElem::layout:Content::layout:FlowElem::layout:Content::layout:BlockElem::layout:Layout::measure:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.703858Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout:FlowElem::layout:FlowLayouter::layout_par:ParElement::layout:BoxElem::layout:Content::layout:FlowElem::layout:Content::layout:BlockElem::layout:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.705065Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout:FlowElem::layout:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.705678Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout:FlowElem::layout:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.706207Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout:FlowElem::layout:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.709470Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout:FlowElem::layout:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.711174Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout:FlowElem::layout:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.711297Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout:FlowElem::layout:Content::layout:BlockElem::layout:Layout::measure:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.721148Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout:FlowElem::layout:Content::layout:BlockElem::layout:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:44:54.728089Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Layouting page #1
2024-03-14T02:44:54.728140Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Layouting header
2024-03-14T02:44:54.728160Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Layouting footer
2024-03-14T02:44:54.728177Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Layouting background
2024-03-14T02:44:54.728194Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Layouting foreground
2024-03-14T02:44:54.973097Z  WARN naga_oil::compose::parse_imports: item list imports are deprecated, please use `rust::style::item_imports` (or use feature `allow_deprecated`)`
| #import bevy_render::view View

2024-03-14T02:44:54.974338Z  WARN naga_oil::compose::parse_imports: item list imports are deprecated, please use `rust::style::item_imports` (or use feature `allow_deprecated`)`
| #import bevy_render::view View

zsh: segmentation fault (core dumped)  cargo run --example typst_basic
```

**Comment by rousbound** [comment] 2024-03-14 02:48
Also, something similar happens when compiling a simple document (in the "content" variable) such as "hello world!":

```rust
[user@machine  in .../Tests/bevy_motiongfx]
 >> $ cargo run --example typst_basic
   Compiling bevy_motiongfx v0.1.0 (Tests/bevy_motiongfx)
    Finished dev [unoptimized + debuginfo] target(s) in 23.49s
     Running `target/debug/examples/typst_basic`
2024-03-14T02:47:46.017078Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-03-14T02:47:46.017516Z  WARN winit::platform_impl::platform::x11::util::randr: XRandR reported that the display's 0mm in size, which is certifiably insane
2024-03-14T02:47:46.017662Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1
libEGL warning: DRI2: failed to authenticate
2024-03-14T02:47:46.081025Z  INFO bevy_render::renderer: AdapterInfo { name: "llvmpipe (LLVM 15.0.7, 256 bits)", vendor: 65541, device: 0, device_type: Cpu, driver: "llvmpipe", driver_info: "Mesa 23.0.4-0ubuntu1~22.04.1 (LLVM 15.0.7)", backend: Vulkan }
2024-03-14T02:47:46.394739Z  WARN naga_oil::compose::parse_imports: item list imports are deprecated, please use `rust::style::item_imports` (or use feature `allow_deprecated`)`
| #import bevy_render::view View

2024-03-14T02:47:48.010962Z  INFO compile: typst: Layout iteration 0
2024-03-14T02:47:48.011038Z  INFO compile:Content::layout_root: typst::layout: Starting layout
2024-03-14T02:47:48.011152Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux 22.04 Ubuntu", kernel: "6.5.0-25-generic", cpu: "12th Gen Intel(R) Core(TM) i9-12900K", core_count: "12", memory: "31.3 GiB" }
2024-03-14T02:47:48.011326Z  INFO compile:Content::layout_root:DocumentElem::layout_root: typst::model::document: Document layout
2024-03-14T02:47:48.011360Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Page layout
2024-03-14T02:47:48.011454Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout:Content::layout: typst::layout: Layouting `Content`
2024-03-14T02:47:48.013424Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Layouting page #1
2024-03-14T02:47:48.013471Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Layouting header
2024-03-14T02:47:48.013491Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Layouting footer
2024-03-14T02:47:48.013505Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Layouting background
2024-03-14T02:47:48.013515Z  INFO compile:Content::layout_root:DocumentElem::layout_root:layout: typst::layout::page: Layouting foreground
2024-03-14T02:47:48.175940Z  WARN naga_oil::compose::parse_imports: item list imports are deprecated, please use `rust::style::item_imports` (or use feature `allow_deprecated`)`
| #import bevy_render::view View

2024-03-14T02:47:48.176882Z  WARN naga_oil::compose::parse_imports: item list imports are deprecated, please use `rust::style::item_imports` (or use feature `allow_deprecated`)`
| #import bevy_render::view View

zsh: segmentation fault (core dumped)  cargo run --example typst_basic
``

**Comment by nixon-voxell** [comment] 2024-03-14 02:59
hey @rousbound 

is your content like so
```rs
    let content = String::from(
        r###"
        hello world
        "###,
    );
```

just to confirm.

**Comment by mattfbacon** [comment] 2024-03-14 06:02
Cannot reproduce on Arch Linux with sway compositor. After removing the monokai theme part, the document renders normally with no errors.

**Comment by mattfbacon** [comment] 2024-03-14 06:05
BTW, you may also try running the binary within gdb and getting a backtrace with `bt` after the segmetation fault (which gdb will catch).

**Comment by AbstractiveNord** [comment] 2024-03-21 08:57
@mattfbacon check out #38 , your problem should be fixed.

**Comment by nixon-voxell** [comment] 2024-03-21 09:01
> @mattfbacon check out #38 , your problem should be fixed.

@mattfbacon 's error involve segmentation fault tho, still abit unsure what is causing that XD

**Comment by AbstractiveNord** [comment] 2024-03-21 09:05
> > @mattfbacon check out #38 , your problem should be fixed.
> 
> @mattfbacon 's error involve segmentation fault tho, still abit unsure what is causing that XD

I have some experience with Bevy, which have segmentation fault caused by mp3 instead of wav or something like that. Also ping Matt should help you fix that issue.

**Comment by AbstractiveNord** [comment] 2024-03-21 09:06
I missed with topic starter ping. That's @rousbound to check code now.

**Comment by nixon-voxell** [comment] 2024-05-12 13:47
Hey I am going to close this for now, feel free to reopen it if the issue still exists.

**Closed by nixon-voxell** 2024-05-12 13:47 UTC
Labels: bug
